### Create Project Member
POST http://localhost:8888/projectMembers/create
Content-Type: application/json
Accept: application/json

{
  "projectMemberProjectId": 1,
  "projectMemberEmployeeId": "EP019",
  "projectMemberRoleId": 10603,
  "projectMemberEmployeeName": "이재원"
}

### Create Project Member
POST http://localhost:8888/projectMembers/create
Content-Type: application/json
Accept: application/json

{
  "projectMemberProjectId": 1,
  "projectMemberEmployeeId": "EP027",
  "projectMemberRoleId": 10603,
  "projectMemberEmployeeName": "조예린"
}

### Create Project Member
POST http://localhost:8888/projectMembers/create
Content-Type: application/json
Accept: application/json

{
  "projectMemberProjectId": 1,
  "projectMemberEmployeeId": "EP028",
  "projectMemberRoleId": 10603,
  "projectMemberEmployeeName": "지현근"
}

### Create Project Member
POST http://localhost:8888/projectMembers/create
Content-Type: application/json
Accept: application/json

{
  "projectMemberProjectId": 1,
  "projectMemberEmployeeId": "EP029",
  "projectMemberRoleId": 10603,
  "projectMemberEmployeeName": "최종찬"
}



### View Project Members By Project
GET http://localhost:8888/projectMembers/list/2
Accept: application/json

###

# View and Search Available Members
GET http://localhost:8888/projectMembers/available/2?query=수정
Accept: application/json

###


# Remove Project Member
DELETE http://localhost:8888/projectMembers/remove/2
Content-Type: application/json
Accept: application/json

{
  "projectMemberHistoryReason": "Some reason for removal"
}

###

# Modify Project Member
PUT http://localhost:8888/projectMembers/modify
Content-Type: application/json
Accept: application/json

{
  "projectMemberId": 2,
  "projectMemberRoleId": 10601
}
