// 완료

### 프로젝트 생성
POST http://localhost:8888/projects/create
Content-Type: application/json

{
    "projectTitle": "오목눈이 프로젝트",
    "projectStartDate": "2024-05-01",
    "projectEndDate": "2024-06-14",
    "projectStatus": "진행",
    "employeeId" : "EP023",
    "employeeName": "장민석"
}



### 프로젝트 수정
PUT http://localhost:8888/projects/modify
Content-Type: application/json

{
  "projectId": 1,
  "projectHistoryReason": "프로젝트 수정 사유 : 집에 가야해서",
  "projectHistoryProjectMemberId" : 1,
  "projectMemberId" : 1,
  "projectTitle" : "수정된 프로젝트 제목입니다",
  "projectStartDate" : "2024-05-09T12:00:00Z",
  "projectEndDate" : "2024-06-14T12:00:00Z"
}

### 프로젝트 일정 10등분
GET http://localhost:8888/projects/workingDaysDivideTen?startDate=2023-01-01&endDate=2023-12-31

### 프로젝트 복사(프로젝트, 일정)
POST http://localhost:8888/projects/copy/1

### 프로젝트 목록 조회
GET http://localhost:8888/projects/list/EP001

### 프로젝트 상세 조회
GET http://localhost:8888/projects/view/2

